import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/components/providers/AuthProvider'
import RegisterModal from '@/components/modals/RegisterModal'
import LoginModal from '@/components/modals/LoginModal'
import { Toaster } from '@/components/ui/toaster'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Code',
  description: 'Generated by create next app',
  keywords:"react,Next js farsi amozesh amozesh React amozesh Nxt JS",
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body className="  ">
        <AuthProvider>
        <LoginModal/>
        <RegisterModal/>

        {children}
        <Toaster/>
        </AuthProvider>
        
        </body>
    </html>
  )
}
